name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Archive Build
      run: tar -czf build.tar.gz .next public package.json package-lock.json

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Copy Build to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no build.tar.gz root@<your-server-ip>:/var/www/next-app/

    - name: Deploy Application on Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no root@<your-server-ip> << 'EOF'
          cd /var/www/next-app/
          tar -xzf build.tar.gz
          npm ci --production
          pm2 stop next-app || true
          pm2 start npm --name "next-app" -- start
        EOF
